
java: 'https://adoptium.net/temurin/releases/?os=windows&version=17&package=jdk'

modpack: 'https://drive.google.com/uc?id=1cYfe-27LlfAh-NVt9NGVjR--Rs14aP33'

farlands_discord: 'https://discord.gg/F9DhMsGZ'

modrinth: 'https://modrinth.com/app'

curseforge: 'https://www.curseforge.com/download/app'

forge_standalone: 'https://drive.google.com/uc?id=1kEhlAW0zZjOcfYZj6hEFqe1NvK_BWvUW'


